# Generated by Django 2.0.5 on 2018-05-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstSolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scz_department',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_menu',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_parameter',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_role',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_rolepermit',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_user',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_user',
            name='Lastlogontime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_userdepartment',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scz_userrole',
            name='LaseWriteTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='scz_department',
            table='SCZ_Department',
        ),
        migrations.AlterModelTable(
            name='scz_menu',
            table='SCZ_Menu',
        ),
        migrations.AlterModelTable(
            name='scz_parameter',
            table='SCZ_Parameter',
        ),
        migrations.AlterModelTable(
            name='scz_role',
            table='SCZ_Role',
        ),
        migrations.AlterModelTable(
            name='scz_rolepermit',
            table='SCZ_RolePermit',
        ),
        migrations.AlterModelTable(
            name='scz_user',
            table='SCZ_User',
        ),
        migrations.AlterModelTable(
            name='scz_userdepartment',
            table='SCZ_UserDepartment',
        ),
        migrations.AlterModelTable(
            name='scz_userrole',
            table='SCZ_UserRole',
        ),
    ]
